### ISSUE TITLE
Improve/add visual indication of collapsed posts

### ISSUE THREAD

**Issue by neatchee** [neatchee/mastodon#10]
### Pitch

Add a visual indication of a collapsed post to the bottom of the collapsed post (such as a small "tab" that says "vvv Expand vvv") overlaying the faded text

### Motivation

It is difficult to spot collapsed posts at a glance when scrolling timelines. The small expand button at the top right of the post blends in with other UI, faded text is subtle, and the glitch-soc setting to add a background to collapsed posts is jarring af.

**Comment by deanveloper** [comment]
Working on this right now. My main issue is that... it just doesn't look very good. Not quite sure what to do to fix it.

<details><summary>trying different arrows</summary>
Double-down arrows (my favorite)

<img src="https://user-images.githubusercontent.com/3196327/210028828-72b8dca7-9ad2-475c-a70f-69988c30eecd.png" />

Emojis (ew)
<img src="https://user-images.githubusercontent.com/3196327/210028758-2bf56b5e-6023-43db-b16d-ff48c36f1556.png" />

v's (not bad, not great)
<img src="https://user-images.githubusercontent.com/3196327/210028815-beb7de6b-ec43-4c4b-b93e-e881ae8b3ca8.png" />
</details>

I think I'll be toying around with color and stuff a bit more before pushing. Still doesn't look quite right.

**Comment by deanveloper** [comment]
Alright, I think I've got something I'm satisfied with, let me know if there's any feedback. I'll open the PR now
![image](https://user-images.githubusercontent.com/3196327/210034811-311fa6a9-152e-4582-bc0b-6ab628b54120.png)
