### ISSUE TITLE
Old posts sometimes inserted into the timeline

### ISSUE THREAD

**Issue by deanveloper** [neatchee/mastodon#25]
### Steps to reproduce the problem

1. Keep home timeline open for a bit
2. Notice that every once in a while, day-old posts are inserted into the timeline

I'm not sure if this issue is specific to the user/instance, but it seems to happen with `@gaycats@botsin.space` pretty often. I've seen it happen with other users too, but that's the most common one I think.

### Expected behaviour

Old posts should at the very least be sorted to be lower in the timeline

### Actual behaviour

Old posts appear at the top of the timeline

### Detailed description

This is what it looks like

![image](https://user-images.githubusercontent.com/3196327/210194300-7e6d58ac-c50b-4f95-b5c0-9ce1846d35ff.png)

I also managed to also catch it in debugger, so here is the post which got sent over the statuses websocket connection:
https://gist.github.com/deanveloper/6b735b8e38909610363943f981013d49

Which means that the backend is, for some reason, sending old posts through the websocket connection. This might be intended, I'm not quite sure. But I feel like the frontend should at least be sorting the old posts lower.

### Specifications

Chrome Version 108.0.5359.125 (Official Build) (64-bit)

v4.0.2+glitch

**Comment by deanveloper** [comment]
For the record, this is probably a mastodon/glitch-soc bug but I'm not sure

**Comment by neatchee** [comment]
I think this is intended design: The federated feed displays anything that is interacted with by users on our instance, right? If one of our users favorites a day old post, that post will show up in the federated feed shortly thereafter despite being a day old.

**Comment by deanveloper** [comment]
https://urusai.social/@gaycats@botsin.space/109603022970728801

![image](https://user-images.githubusercontent.com/3196327/210218174-78867c05-7ba4-44b1-ac92-134a9710da03.png)

This 2 day old post appears to be entirely unprompted - no favorites nor boosts (within our federation). I think you might be right with the stale request. It just seems weird how often this occurs, and it's almost always with this exact account. Granted I don't know if I follow any other accounts from botsin.space.

Possible solutions could be either to implement this on the frontend by sorting the post into the correct spot, or on the backend by doing a quick "recency" check (ie, only posts/boosts from the last 5 minutes will be sent over pubsub/websockets)

**Comment by neatchee** [comment]
So, keep in mind, we federate with a relay. Relay-provided posts won't show follows unless you click all the way through to their instance (and they have it visible).

**Comment by neatchee** [comment]
Nevermind, there's definitely someone up. I'm rolling back the public boost feature too see if that resolves it as only posts within the past 3 days are showing this behavior

**Comment by neatchee** [comment]
Ok, so before reverting Sidekiq was showing a ton of retry entries with a "missing argument" error related to "silenced_account_ids". I _think_ this is the culprit line: https://github.com/neatchee/mastodon/blob/a2e504422fcc2011b85d16ca13bf776875faf178/app/services/fan_out_on_write_service.rb#L135

Note that in the function immediately preceding that line we have a second argument in the publish function for "anonymous_payload"

I'm like 99% sure that's it as that payload contains the rendered_status variable which I would assume is how the timeline filters out things like old posts from appearing a second time on the home timeline due to new boosts/etc and how post publishing works.

Testing that as a fix now.

**Comment by deanveloper** [comment]
Yeah I'm almost certain that's the issue. Glad sidekiq logged it! My bad, I'll take a look to see if there's some Ruby tooling in VSCode that will catch stuff like before it's an issue at runtime.

**Comment by neatchee** [comment]
Upside, that may be (at least part of) the feature(s) we need to pipe through to the local/federated timelines to help with suppressing duplicate boosts when that's enabled :D
