### ISSUE TITLE
[frontend-only] Option to combine similar notifications into a single notification

### ISSUE THREAD

**Issue by deanveloper** [neatchee/mastodon#33]
### Pitch

![image](https://user-images.githubusercontent.com/3196327/211022853-4f63b211-e0a1-45f2-ad3f-769469015239.png)

For stuff like this, I'd love to still get notified, but I'd like it better if the notifications were combined into a single "User1, User2, and x others recently favorited your post"

### Motivation

It makes notifications quite hard to read when there are so many favorited items in my notifications column. I'd love to see that they favorited the post in my notifications, but having so many notifications is a bit too much.

**Comment by deanveloper** [comment]
Here's a quick mock of what it could look like. The "2 others" could expand to everyone who's favorited your post when you click it as well.

![image](https://user-images.githubusercontent.com/3196327/211024391-ca0f107f-b626-480f-b11a-811c9279587e.png)

**Comment by neatchee** [comment]
FediLab implements this and I'm a big fan. Definitely want this!

**Comment by deanveloper** [comment]
Interestingly, there's a `<AvatarComposite>` component that we can use, i think right now it's only really used for DMs.

Even more interestingly, it's imported into status_header (the component that renders "{acct} has favourited your post" unused, meaning it looks like either this was already a feature at one point, or it's a feature that someone wanted to work on but never fully went through.

**Comment by deanveloper** [comment]
> Even more interestingly, it's imported into status_header (the component that renders "{acct} has favourited your post" unused, meaning it looks like either this was already a feature at one point, or it's a feature that someone wanted to work on but never fully went through.

btw this is a lie, unfortunately I don't think we can use AvatarComposite for our use-case

**Comment by deanveloper** [comment]
Alright, I have something whipped up. Going to do some extra local testing and then create the PR into master for some review. So far, this touches quite a bit of code, so it might cause some merge conflicts whenever we want to merge upstream in. This is because I had to change the `account` property in notifications and statuses from a single object to a list of objects, so quite a lot of logic had to change to deal with that.

![image](https://user-images.githubusercontent.com/3196327/215316084-26f2b230-ac9b-4c44-b045-37e02a08a0b8.png)

Also just noticed that now profile icons aren't rendering... time to figure that out ahaha
