### ISSUE TITLE
The emoji picker is not forced within the screen bounds

### ISSUE THREAD

**Issue by neatchee** [neatchee/mastodon#40]
### Steps to reproduce the problem

1. On mobile, navigate to a status with enough replies to make it necessary to scroll
2. Scroll to the last reply
3. Click/tap the react (+) button on the last reply. It should be nearly flush against the bottom of the window

### Expected behaviour

Emoji picker opens with its bottom edge positioned at the screen edge

### Actual behaviour

Emoji picker is almost entirely off-sceen, having used the react button as its positioning anchor

### Detailed description

If the anchor for the emoji picker (emoji button, react button) is too close to the screen/window edge, the picker will float outside the screen bounds and make some of all of it inaccessible 

### Specifications

neatchee/mastodon/main

**Comment by neatchee** [comment]
I think this would be handled in the Overlay element of app/javascript/flavours/glitch/features/compose/components/emoji_picker_dropdown.js @ line 393

I think it needs to have the 'preventOverflow' modifier with the 'boundariesElement' option set to 'viewport' or 'window'
But my attempts to actually implement it failed.

**Comment by IRod22** [comment]
@neatchee, I'm looking into whether [`reactjs-popup`](https://www.npmjs.com/package/reactjs-popup) will be a good fit or not, but based on the demo on the readme, this package may not be the best option. Let me do some more digging.

**Comment by IRod22** [comment]
BTW, with how GitHub works, if you type something like `https://github.com/neatchee/mastodon/blob/<commit-hash>/<path-to-file>#L<line-number>`, you can view a line of code from a file in a commit. Here is L393 of the file in question:

https://github.com/neatchee/mastodon/blob/58291b7f507ea5e688e412009df301983d80b1f7/app/javascript/flavours/glitch/features/compose/components/emoji_picker_dropdown.jsx#L393

**Comment by neatchee** [comment]
I strongly recommend you do not make any package changes, as that will
break upstream compatibility significantly. First, see if you can modify
the existing React code to achieve the specific feature/fix this issue is
looking to resolve in the simplest way possible.

If there's a compelling reason to move away from the emojimart, that's
something I'd want to iterate on extensively and really research the best
option for the project.

**Comment by IRod22** [comment]
@neatchee let me dig into `react-overlays` later on. Unless I'm wrong, I think the answer may be with the `More` overlay (that is open when the `More` button, right from the `Bookmark` button, is clicked).

**Comment by IRod22** [comment]
I think I found what the issue is. According to the docs, the [`flip`](https://react-bootstrap.github.io/react-overlays/api/Overlay#flip) prop should do the trick:

```diff
-         <Overlay show={active} placement={'bottom'} target={this.findTarget} popperConfig={{ strategy: 'fixed' }}>
+         <Overlay show={active} placement={'bottom'} flip target={this.findTarget} popperConfig={{ strategy: 'fixed' }}>
```

See also:
- https://github.com/neatchee/mastodon/blob/58291b7f507ea5e688e412009df301983d80b1f7/app/javascript/flavours/glitch/features/compose/components/dropdown.jsx#L214-L222
  Look at line 218.

---

I'm ready to implement the changes; I just need the green light to do so.
