### ISSUE TITLE
Emoji Reactions not converting to Favourites on Vanilla Mastodon instances

### ISSUE THREAD

**Issue by Tobleh** [neatchee/mastodon#76]
### Steps to reproduce the problem

1. Using the Glitch+Urusai fork of Mastodon (via sakurajima.moe, v4.2.0-rc2+glitch), I send an emoji reaction to a post from an instance using the vanilla version of Mastodon (mastodon.social, v4.2.0).
2. Looking at the the post on the home instance, I refresh the page, check the favourites counter, and check the list of users who favourited the post.
3. After that, using a Firefish instance (via sakurajima.social, Firefish v1.0.3), I send another emoji reaction to the same post on mastodon.social.
4. I come back to looking at the post on the home instance (mastodon.social) and perform the same procedure - refreshing the page, checking the favourties counter, and checking the list of users who favourited the post.

[Screencast from 2023-09-22 12-33-58.webm](https://github.com/neatchee/mastodon/assets/65689818/e4d0ac4e-dc77-4151-b9f3-871ff5c9d1df)
...

### Expected behaviour

Both emoji reactions should have been counted as a favourite for the user on mastodon.social to give a total count of "2" favourites, and both the users from sakurajima.moe and sakurajima.social should have shown up in the list of users who favourited the post.

### Actual behaviour

The emote reaction from sakurajima.moe never registers for the user on mastodon.social as a favourite. Only the reaction from sakurajima.social gets registered as a "favourite", giving a total count of "1" favourite..

### Detailed description

I tested this function using my main account @tobleh@sakurajima.moe, I posted the test post using a test account for vanilla Mastodon instances @tobleh@mastodon.social, and I used my Firefish test account @tobleh@sakurajima.social as the closest thing that I have to a control in regards to a Misskey/Firefish/Pleroma/Akkoma user sending an emoji reaction.

The expected behaviour is that the Glitch+Urusai fork should perform the same as Misskey/Firefish/Pleroma/Akkoma when it comes to giving emoji reactions to a post on vanilla Mastodon - converting that reaction into a "favourite" for a user on a vanilla Mastodon instance.

Instead, the reaction from the Glitch+Urusai fork does not get converted into a "favourite" for the user on the vanilla Mastodon instance.

### Mastodon instance

sakurajima.moe

### Mastodon version

v4.2.0-rc2+glitch

### Browser name and version

Firefox 117.0.1 (64-bit) for Arch Linux.

### Operating system

Arch Linux x86_64, Linux kernel 6.5.3-arch1-1

**Comment by neatchee** [comment]
This sounds like an implementation decision; the important distinction here is that Firefish/Misskey don't distinguish between favorites and reactions internally. They chose to have the mastodon compatibility later collapse all reactions into a single "favorite reaction". For Mastodon's reaction implementation, however, Favorite and Reaction are treated independently; you can Favorite AND React to the same post (which is great when you want to negatively react to something)

Upstream implementation will need to decide whether or not they want to move Favorite into Reactions as just a type of reaction. Then it would make sense to do the same thing Firefish/Misskey does.

I'll open an issue upstream, but I don't think it will be looked at until the v0 Reaction code is merged into glitch-soc.
