### ISSUE TITLE
mp3 uploads not playing

### ISSUE THREAD

**Issue by AmiTheCat** [neatchee/mastodon#78]
### Steps to reproduce the problem

1. upload an mp3 in a post
2. preview or publish it
3.
...

### Expected behaviour

the mp3 should play in preview and in the post after publishing

### Actual behaviour

it doesn't play, hitting "play" does nothing

### Detailed description

Uploaded mp3s on Urusai no longer play. This has been an issue for at least several months.  They used to play, and I have several mp3 posts I made in the past that worked that no longer do.  This issue effects both old mp3 uploads and new ones and happens both before the post is published (the mp3s don't play in the preview mode or on the "edit description" screen to add captions) and after.  There is no error message.  The mp3 uploads seemingly fine, the post is published seemingly fine, but the mp3 just doesn't play when you hit the play button, nothing happens.

The mp3s seem to play fine on my megalodon app.

### Mastodon instance

urusai.social

### Mastodon version

v4.3.0-alpha.0+glitch

### Browser name and version

Firefox 121.0

### Operating system

Windows 10

**Comment by neatchee** [comment]
Resolved. This is working now!

NOTES: CORS configuration for S3 bucket was missing
